import {Roboto, Montserrat} from "next/font/google";
import "./globals.css";

const montserrat = Montserrat({
  subsets: ["latin"],
  display: "swap",
  weight: ["300","400","500","600","800"],
});

const roboto = Roboto({
  subsets: ["latin"],
  display: "swap",
  weight: ["300","400","500","600","800"],
});

export const metadata = {
  title: "Task Managery",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" translate="no">
      <head>
        <meta name="google" content="notranslate" />
      </head>
      <body className={`${montserrat.className} ${roboto.className}`} >
        {children}
      </body>
    </html>
  );
}